# Generated by Django 5.1.2 on 2024-10-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_book_options_book_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
